### ISSUE TITLE
Key and Cipher methods 

### ISSUE THREAD

**Issue by amirjalali65** [aymanmadkour/ope#1]
Is there any specific reason that encryption/decryption methods are part of the `Key` class instead of `Cipher`. In general, an instance of `Cipher` is generated using a `Key` and encryption/decryption are performed in `Cipher` objects.

**Comment by aymanmadkour** [comment]
Sorry, it has been a while since I looked into this. I guess the naming convention here is a bit different from the standard Java cryptography API.

The way I see it is that you use the `Key` to encrypt/decrypt, so this is why the `Key` object has all the functionality. `Cipher` is simply a factory class for `Key`.
